# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
import numpy as np
print(np.__version__)

1.18.1


#### 3. Create a null vector of size 10

In [4]:
import numpy as np
vector=np.random.random((1,10))
print(vector)

[[0.29503996 0.75390209 0.31176404 0.25506071 0.45197486 0.87751364
  0.77336775 0.82818489 0.64057432 0.77336034]]


#### 4.  How to find the memory size of any array

In [5]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size * n.itemsize))

128 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [30]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [ ]:
import numpy as np
np.zeroes(1,10)

#### 7.  Create a vector with values ranging from 10 to 49

In [8]:
import numpy as np
vector=np.arange(10,50,1)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [11]:
import numpy as np
x=np.arange(0,6)
x=x[::-1]
print(x)

[5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr=np.array([[0,2,3],[4,5,6],[7,8,1]])
print(arr)

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [14]:
import numpy as np
x = np.array([1,2,0,0,4,0])
np.argwhere(x!= 0)

array([[0],
       [1],
       [4]], dtype=int64)

#### 11. Create a 3x3 identity matrix

In [15]:
import numpy as np
arr=np.identity(3)
print('3x3 matrix:')
print(arr)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [ ]:
import numpy as np
x=np.random.random(3,3,3)
print(x)

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [17]:
import numpy as np
x=np.random.random((10,10))
print(x)
print("Max: ",x.max())
print("Min: ",x.min())

Max:  0.9768599527027416
Min:  0.0018587280504142045


#### 14. Create a random vector of size 30 and find the mean value

In [18]:
import numpy as np
x=np.random.random((1,30))
c=x.mean()
print(x)
print(c)

[[0.98420971 0.45179494 0.53221204 0.74576821 0.50547335 0.91421262
  0.69413216 0.03597246 0.86794273 0.14530334 0.88730546 0.23240072
  0.46548958 0.99887018 0.12371461 0.380014   0.66006785 0.67238951
  0.07055202 0.6040767  0.03955455 0.5319399  0.00939757 0.25385233
  0.48644988 0.69123777 0.52406708 0.77935991 0.71856136 0.31411751]]
0.5106813362236479


#### 15. Create a 2d array with 1 on the border and 0 inside

In [21]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [ ]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [32]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [23]:
import numpy as np
arr=np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [22]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [24]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
